wip
diplodoc-platform/markdown-it-markdown-renderer pull request #54
Opened 2023-07-03 12:36 UTC by v8tenko

2023-07-28 07:52 UTC, moki requested changes

2023-07-28 07:52 UTC, moki commented on __tests__/rules/diplodoc/__fixtures__/term.ts
> +
two extra new lines where are they coming from?

2023-07-28 07:52 UTC, moki commented on __tests__/rules/diplodoc/__fixtures__/term.ts
> +1. привет
you use lists in tests but you do not test what happens when term content is aligned with them(you should)

2023-07-28 07:52 UTC, moki commented on src/renderer/index.ts
> +> extends CustomRenderer<T> {
this is outside of the scope of this PR

2023-07-28 07:52 UTC, moki commented on src/rules/diplodoc/term.ts
> +const allways =
its one l in always

2023-07-28 07:52 UTC, moki commented on src/rules/diplodoc/term.ts
> +        const rendered = this.EOL.repeat(2) + `[*${key}]: `;
what happens when template is first in the token stream?

what happens when it is aligned with something other than paragraph?

you should have test cases for that and handle that appropriately.

2023-07-28 07:52 UTC, moki commented on src/rules/diplodoc/term.ts
> +        return this.EOL.repeat(2);
same as above naive new line separation with everything wouldn't cut it

2023-08-04 09:56 UTC, moki requested changes
should term content "[*ключ_термина]: content..." be able to render inside the list item?

like this:

```
1. content
   [*ключ_термина]: content...
2. [*ключ_термина_1]: content...
```

theoretically since it is block container it should

we need test cases for it.

2023-08-04 09:56 UTC, moki commented on __tests__/rules/diplodoc/__fixtures__/term.ts
> +
this is an extra new line

check if "[*ключ_термина]:" token is last in the token stream, if so prevent rendering new line.

2023-08-07 12:01 UTC, v8tenko commented on __tests__/rules/diplodoc/__fixtures__/term.ts
> +
first test is about it

2023-08-07 13:00 UTC, moki commented on __tests__/rules/diplodoc/__fixtures__/term.ts
> +
you have an extra new line in the end.

if this test colored green, then it means you have an error.

you should not have empty new line in the end.

2023-08-07 14:25 UTC, moki commented on src/rules/diplodoc/term.ts
> +        if (!isLast && (!this.state.term.didRenderEOL || shouldSeparate(next))) {
you can completely move logic if it should be separated with new line inside `shouldSeparate` function.

just `call`/`apply` with appropriate this context

2023-08-07 14:35 UTC, moki commented on src/rules/diplodoc/term.ts
> +    if (token.type === 'bullet_list_close' || token.type === 'ordered_list_close') {
these conditions could be merged.

2023-08-07 15:08 UTC, merged